### ISSUE TITLE
Migração de domínio

### ISSUE THREAD

**Issue by vitormattos** [e-cidade/site#2]
Hoje o site está no domínio temporário [site-ecidade.librecode.coop](site-ecidade.librecode.coop)

O site deve ser movido para o domínio ecidade.softwarepublico.org

## To-do

- [ ] Colocar link no menu do site para acessar o fórum
- [ ] Buscar e substituir todas as ocorrências da URL temporária pela URL definitiva
- [ ] Decidir qual será a URL do fórum.
    **Sugestão de URL**: [forum.ecidade.softwarepublico.org](forum.ecidade.softwarepublico.org). Motivo: Com esta URL não precisa implementar regras de proxy em um nginx baseado no path.

## ⚠️ Ponto crítico ⚠️

> Colocar fórum como path ([ecidade.softwarepublico.org/forum](ecidade.softwarepublico.org/forum)) exige necessidade do deploy não ser hospedado pelo GitHub mas deverá ser feito em um nginx que irá redirecionar requisições via proxy do path /forum para o atual fórum que está rodando com Discourse.

Necessário comentários aqui nesta issue sobre este ponto crítico para decidirmos o que fazer em relação a URL do fórum.
